#pragma once

// ============================================================
// AUTO-GENERATED RE HEADER
// ============================================================
// DLL: CockpitBase.dll
// Class: 
//
// WARNING:
// This is an export-derived RE interface.
// It is NOT a complete ABI reconstruction.
// Validate layout/vtables/calling conventions in Ghidra/x64dbg.
// ============================================================

namespace const_cockpit {
namespace avBasicTimer_class_cockpit {
namespace avActuator_ {

class _unknown
{
public:

    // Exported vftable symbols detected:
    // ordinal=1305 RVA=0x518 const cockpit::avBasicTimer<class cockpit::avActuator>::`vftable'
    // ordinal=1306 RVA=0x519 const cockpit::avBasicTimer<class cockpit::avBasicSensor>::`vftable'
    // ordinal=1307 RVA=0x51A const cockpit::avBasicTimer<class cockpit::avDevice>::`vftable'
    // ordinal=1308 RVA=0x51B const cockpit::avBasicTimer<class cockpit::avLaserSpotDetector>::`vftable'
    // ordinal=1309 RVA=0x51C const cockpit::avBasicTimer<class cockpit::avSimpleRadar>::`vftable'
    // ordinal=1310 RVA=0x51D const cockpit::avBasicTimer<class cockpit::avSimpleWeaponSystem>::`vftable'
    // ordinal=1311 RVA=0x51E const cockpit::avBasicTimer<class cockpit::ccDrawable>::`vftable'
    // ordinal=1315 RVA=0x522 const cockpit::BombSight::`vftable'
    // ordinal=1316 RVA=0x523 const cockpit::ClusterBombSight::`vftable'
    // ordinal=1317 RVA=0x524 const cockpit::ClusterBombSightV2::`vftable'
    // ordinal=1322 RVA=0x529 const cockpit::GestureComplex::`vftable'
    // ordinal=1323 RVA=0x52A const cockpit::GestureComplexImpl::`vftable'
    // ordinal=1324 RVA=0x52B const gunner_AI::GunHandlerAI::`vftable'
    // ordinal=1325 RVA=0x52C const cockpit::GunSight::`vftable'
    // ordinal=1326 RVA=0x52D const cockpit::GyroAirSource::`vftable'
    // ordinal=1327 RVA=0x52E const cockpit::GyroElectricSource::`vftable'
    // ordinal=1328 RVA=0x52F const cockpit::IAvionicsDataProxy::`vftable'
    // ordinal=1329 RVA=0x530 const cockpit::IavIMU::`vftable'
    // ordinal=1330 RVA=0x531 const cockpit::IavINS::`vftable'
    // ordinal=1331 RVA=0x532 const cockpit::navigation::IavImuStateVector::`vftable'
    // ordinal=1332 RVA=0x533 const cockpit::IntercomImplement::`vftable'
    // ordinal=1333 RVA=0x534 const cockpit::LuaCoroutine::`vftable'
    // ordinal=1334 RVA=0x535 const cockpit::MechCanopyCrank::`vftable'
    // ordinal=1335 RVA=0x536 const cockpit::MissileSight::`vftable'
    // ordinal=1336 RVA=0x537 const cockpit::RocketSight::`vftable'
    // ordinal=1337 RVA=0x538 const cockpit::SNS_GPS::`vftable'
    // ordinal=1338 RVA=0x539 const cockpit::SNS_GPS_GLONASS::`vftable'
    // ordinal=1339 RVA=0x53A const cockpit::SNSv2::`vftable'
    // ordinal=1340 RVA=0x53B const cockpit::SightDevice::`vftable'
    // ordinal=1341 RVA=0x53C const gunner_AI::SimpleSightAI::`vftable'
    // ordinal=1342 RVA=0x53D const cockpit::SimpleWeaponSystemSightUpdate::`vftable'
    // ordinal=1343 RVA=0x53E const cockpit::TransferFunction::`vftable'
    // ordinal=1344 RVA=0x53F const cockpit::TransferFunctionAperiodic::`vftable'
    // ordinal=1345 RVA=0x540 const cockpit::TransferFunctionDifferential::`vftable'
    // ordinal=1346 RVA=0x541 const cockpit::TransferFunctionForce::`vftable'
    // ordinal=1347 RVA=0x542 const cockpit::TransferFunctionIntegral::`vftable'
    // ordinal=1348 RVA=0x543 const cockpit::TransferFunctionIntegralLimited::`vftable'
    // ordinal=1349 RVA=0x544 const cockpit::TransferFunctionRealDifferential::`vftable'
    // ordinal=1350 RVA=0x545 const cockpit::ambient_controller::`vftable'
    // ordinal=1351 RVA=0x546 const cockpit::arcade_target::`vftable'
    // ordinal=1352 RVA=0x547 const cockpit::avA11Clock::`vftable'
    // ordinal=1358 RVA=0x54D const cockpit::avABU11Clock::`vftable'
    // ordinal=1361 RVA=0x550 const cockpit::avAChS_1::`vftable'
    // ordinal=1364 RVA=0x553 const cockpit::avADF::`vftable'
    // ordinal=1395 RVA=0x572 const cockpit::avActuator::`vftable'
    // ordinal=1396 RVA=0x573 const cockpit::avActuator_BasicTimer::`vftable'
    // ordinal=1397 RVA=0x574 const cockpit::avAirDrivenDirectionalGyro::`vftable'
    // ordinal=1400 RVA=0x577 const cockpit::avAirDrivenTurnIndicator::`vftable'
    // ordinal=1405 RVA=0x57C const cockpit::avArtificialHorizon::`vftable'
    // ordinal=1408 RVA=0x57F const cockpit::avArtificialHorizont_AN5736::`vftable'
    // ordinal=1413 RVA=0x584 const cockpit::avAvionicsDataProxyDefault::`vftable'
    // ordinal=1414 RVA=0x585 const cockpit::avBaseARC::`vftable'
    // ordinal=1429 RVA=0x594 const cockpit::avBasicElectric::`vftable'
    // ordinal=1445 RVA=0x5A4 const cockpit::avBasicSensor_SearchTimer::`vftable'
    // ordinal=1448 RVA=0x5A7 const cockpit::avBreakable::`vftable'
    // ordinal=1449 RVA=0x5A8 const cockpit::avChaffFlareContainer::`vftable'
    // ordinal=1454 RVA=0x5AD const cockpit::avCommunicator::`vftable'
    // ordinal=1467 RVA=0x5BA const cockpit::avDevice_BasicTimer::`vftable'
    // ordinal=1468 RVA=0x5BB const cockpit::avDirAntenna::`vftable'
    // ordinal=1469 RVA=0x5BC const cockpit::avDirectionalGyro_AN5735::`vftable'
    // ordinal=1472 RVA=0x5BF const cockpit::avDispenseProgram::`vftable'
    // ordinal=1477 RVA=0x5C4 const cockpit::avElectricSourceParamDriven::`vftable'
    // ordinal=1478 RVA=0x5C5 const cockpit::avElectricallyHeldSwitch::`vftable'
    // ordinal=1483 RVA=0x5CA const cockpit::avEmbeddedNavigation::`vftable'
    // ordinal=1510 RVA=0x5E5 const cockpit::avILS::`vftable'
    // ordinal=1513 RVA=0x5E8 const cockpit::avILS_AN_ARN108::`vftable'
    // ordinal=1516 RVA=0x5EB const cockpit::avIMU::`vftable'
    // ordinal=1517 RVA=0x5EC const cockpit::avIMUv2::`vftable'
    // ordinal=1522 RVA=0x5F1 const cockpit::navigation::avINSinterface::`vftable'
    // ordinal=1523 RVA=0x5F2 const cockpit::avINSv2::`vftable'
    // ordinal=1530 RVA=0x5F9 const cockpit::avImuStateVector::`vftable'
    // ordinal=1531 RVA=0x5FA const cockpit::avImuStateVectorV2::`vftable'
    // ordinal=1550 RVA=0x60D const cockpit::avKneeboard::`vftable'
    // ordinal=1555 RVA=0x612 const cockpit::avLaserSpotDetector::`vftable'
    // ordinal=1556 RVA=0x613 const cockpit::avLinkToTargetResponder::`vftable'
    // ordinal=1557 RVA=0x614 const cockpit::avLuaDevice::`vftable'
    // ordinal=1560 RVA=0x617 const cockpit::avLuaRegistrable::`vftable'
    // ordinal=1561 RVA=0x618 const cockpit::avMLWS::`vftable'
    // ordinal=1564 RVA=0x61B const cockpit::avMagneticCompass::`vftable'
    // ordinal=1571 RVA=0x622 const cockpit::avMechCompass::`vftable'
    // ordinal=1576 RVA=0x627 const cockpit::avMechanicClock::`vftable'
    // ordinal=1579 RVA=0x62A const cockpit::avMissionTargetManager::`vftable'
    // ordinal=1580 RVA=0x62B const cockpit::avMovingMap::`vftable'
    // ordinal=1584 RVA=0x62F const cockpit::avMovingMap_Cursor::`vftable'
    // ordinal=1599 RVA=0x63E const cockpit::avPlatform::`vftable'
    // ordinal=1600 RVA=0x63F const cockpit::avPlayerTaskHandler::`vftable'
    // ordinal=1634 RVA=0x661 const cockpit::avReceiver::`vftable'
    // ordinal=1643 RVA=0x66A const cockpit::avRippReleaseCapable::`vftable'
    // ordinal=1644 RVA=0x66B const cockpit::avRollPitchGyro::`vftable'
    // ordinal=1662 RVA=0x67D const cockpit::avSimpleAirspeedIndicator::`vftable'
    // ordinal=1665 RVA=0x680 const cockpit::avSimpleAltimeter::`vftable'
    // ordinal=1668 RVA=0x683 const cockpit::avSimpleElectricSystem::`vftable'
    // ordinal=1671 RVA=0x686 const cockpit::avSimpleMachIndicator::`vftable'
    // ordinal=1682 RVA=0x691 const cockpit::avSimpleRadarTimer::`vftable'
    // ordinal=1683 RVA=0x692 const cockpit::avSimpleTurnSlipIndicator::`vftable'
    // ordinal=1686 RVA=0x695 const cockpit::avSimpleVariometer::`vftable'
    // ordinal=1693 RVA=0x69C const cockpit::avSlipBall::`vftable'
    // ordinal=1694 RVA=0x69D const cockpit::avSlipBallExternalSensors::`vftable'
    // ordinal=1695 RVA=0x69E const cockpit::avSpot_SearchTimer::`vftable'
    // ordinal=1696 RVA=0x69F const cockpit::avSyncable::`vftable'
    // ordinal=1697 RVA=0x6A0 const cockpit::avTACAN::`vftable'
    // ordinal=1700 RVA=0x6A3 const cockpit::avTACAN_ARN118::`vftable'
    // ordinal=1756 RVA=0x6DB const cockpit::avWeap_ReleaseTimer_Activity::`vftable'
    // ordinal=1757 RVA=0x6DC const cockpit::avYawGyro::`vftable'
    // ordinal=1764 RVA=0x6E3 const cockpit::ccArcade_template_buffer::`vftable'
    // ordinal=1767 RVA=0x6E6 const cockpit::ccCachedElementsBuffer::`vftable'
    // ordinal=1768 RVA=0x6E7 const cockpit::ccChart::`vftable'
    // ordinal=1771 RVA=0x6EA const cockpit::ccContextRelatedObject::`vftable'
    // ordinal=1778 RVA=0x6F1 const cockpit::ccDrawable_BasicTimer::`vftable'
    // ordinal=1781 RVA=0x6F4 const cockpit::ccElementAutoUpdater::`vftable'
    // ordinal=1782 RVA=0x6F5 const cockpit::ccIndicationTemplateBuffer::`vftable'
    // ordinal=1785 RVA=0x6F8 const cockpit::ccIndicatorPage::`vftable'
    // ordinal=1790 RVA=0x6FD const cockpit::ccLambdaGauge::`vftable'
    // ordinal=1791 RVA=0x6FE const cockpit::ccMainPanel::`vftable'
    // ordinal=1794 RVA=0x701 const cockpit::ccMapObjectsBuffer::`vftable'
    // ordinal=1795 RVA=0x702 const cockpit::ccMouseHandler::`vftable'
    // ordinal=1796 RVA=0x703 const cockpit::ccMovingMap::`vftable'
    // ordinal=1797 RVA=0x704 const cockpit::ccPanelEffect::`vftable'
    // ordinal=1798 RVA=0x705 const cockpit::ccPanelGauge::`vftable'
    // ordinal=1799 RVA=0x706 const cockpit::ccPanelGaugeCycled::`vftable'
    // ordinal=1800 RVA=0x707 const cockpit::ccPanelGaugeExternalArgToCockpit::`vftable'
    // ordinal=1801 RVA=0x708 const cockpit::ccPanelGaugeForParameter::`vftable'
    // ordinal=1802 RVA=0x709 const cockpit::ccPanelGauge_internal::`vftable'
    // ordinal=1803 RVA=0x70A const cockpit::ccPrivateChart::`vftable'
    // ordinal=1806 RVA=0x70D const cockpit::ceBoundingMeshBox::`vftable'
    // ordinal=1807 RVA=0x70E const cockpit::ceBoundingTexBox::`vftable'
    // ordinal=1808 RVA=0x70F const cockpit::ceCircle::`vftable'
    // ordinal=1811 RVA=0x712 const cockpit::ceGeometryClone::`vftable'
    // ordinal=1812 RVA=0x713 const cockpit::ceHWLine::`vftable'
    // ordinal=1813 RVA=0x714 const cockpit::ceHWSector::`vftable'
    // ordinal=1814 RVA=0x715 const cockpit::ceHint::`vftable'
    // ordinal=1815 RVA=0x716 const cockpit::ceMeshPoly::`vftable'
    // ordinal=1816 RVA=0x717 const cockpit::ceParsedElement::`vftable'
    // ordinal=1817 RVA=0x718 const cockpit::ceSCircle::`vftable'
    // ordinal=1818 RVA=0x719 const cockpit::ceSMultiLine::`vftable'
    // ordinal=1819 RVA=0x71A const cockpit::ceSVarLenLine::`vftable'
    // ordinal=1820 RVA=0x71B const cockpit::ceSimple::`vftable'
    // ordinal=1821 RVA=0x71C const cockpit::ceSimpleLineObject::`vftable'
    // ordinal=1822 RVA=0x71D const cockpit::ceTMultiLine::`vftable'
    // ordinal=1823 RVA=0x71E const cockpit::ceTexPoly::`vftable'
    // ordinal=1824 RVA=0x71F const cockpit::chart_item::`vftable'
    // ordinal=1849 RVA=0x738 const cockpit::flood_light_controller::`vftable'
    // ordinal=1850 RVA=0x739 const cockpit::gauge::`vftable'
    // ordinal=1851 RVA=0x73A const cockpit::gauge_limited::`vftable'
    // ordinal=1852 RVA=0x73B const cockpit::gauge_linear::`vftable'
    // ordinal=1853 RVA=0x73C const cockpit::gauge_periodic::`vftable'
    // ordinal=1854 RVA=0x73D const cockpit::gear_handle::`vftable'
    // ordinal=1855 RVA=0x73E const cockpit::light_arg_controller::`vftable'
    // ordinal=1856 RVA=0x73F const cockpit::mission_target::`vftable'
    // ordinal=1857 RVA=0x740 const cockpit::mov_ptr_mark::`vftable'

    // No exported methods were recovered.
};

} // namespace avActuator_
} // namespace avBasicTimer_class_cockpit
} // namespace const_cockpit

// DCS_OPS_RE_COCKPITBASE.DLL__HPP
