dofile("Scripts//targetview//_targetViewCommon.lua")

-- w = 512 --source width
-- h = 512	-- source height
w = 256 --source width
h = 256	-- source height

function getName(name, downsampling)
	downsampling = downsampling or 1
	return string.format("%s_%dx%d", name, tostring(math.floor(w/downsampling)), tostring(math.floor(h/downsampling)))
end

function getBRDFTableName(name, samplesX, samplesY)
	downsampling = downsampling or 1
	return string.format("%s_%dx%d", name, tostring((samplesX+1)*(samplesX*samplesY)), tostring(samplesY))
end

targetView.addRow(32)
targetView.addRow(256)
-- targetView.addRow(128)
-- targetView.addRow(128)
-- targetView.addRow(128)

-- targetView.addTarget('BRDFTable_343x7',1, 24)
-- targetView.addTarget(getBRDFTableName('BRDFTable', 7,7), 1, 64)
-- targetView.addTarget(getBRDFTableName('BRDFTable', 8,8), 1, 64)
targetView.addTarget('BRDFTable',  1, 64)

targetView.addTarget('hdrBufferBR0', 2)
targetView.addTarget(getName('tmpDownsampled',32), 2)
targetView.addTarget('BRDFSampleReference', 2)
targetView.addTarget('BRDFSample', 2)
targetView.addTarget('BRDFSphere', 2)
