dofile("Scripts//targetview//_targetViewCommon.lua")

targetView.addRow(240)

targetView.addCubeHemisphereTop('CockpitCube0', 1, 0);
targetView.addCubeHemisphereBottom('CockpitCube0', 1, 0);
targetView.addCubeHemisphereTop('CockpitCube0', 1, 8)
targetView.addCubeHemisphereBottom('CockpitCube0', 1, 8)

targetView.addCubeHemisphereTop('CockpitCubeAlbedo', 1, 0);
targetView.addCubeHemisphereBottom('CockpitCubeAlbedo', 1, 0);
targetView.addCubeHemisphereTop('CockpitCubeNormal', 1, 8)
targetView.addCubeHemisphereBottom('CockpitCubeNormal', 1, 8)

