dofile("Scripts//targetview//_targetViewCommon.lua")

targetView.addRow(128)
targetView.addRow(128)

for i=0,8 do targetView.addCubeHemisphereTop('EnvCube', 1, i) end
for i=0,8 do targetView.addCubeHemisphereBottom('EnvCube', 2, i) end

targetView.addCubeHemisphereTop('cloudsCube', 1, 0)
targetView.addCubeHemisphereBottom('cloudsCube', 2, 0)

targetView.addTarget('SurfaceAmbient', 1)
targetView.addTarget('SurfaceAmbient2', 2)

targetView.addTarget('preintegratedGF', 1)
