dofile("Scripts//targetview//_targetViewCommon.lua")

sz = 256 -- view size

targetView.addRow(sz)

-- targetView.addTarget('testTex',			 1, 1);
targetView.addTarget('RefractionColor',		 1, 1);
targetView.addTarget('Target::Reflection',	 1, 1);
targetView.addTarget('BowwaveColor',		 1, 1);
targetView.addTarget('light.rend',			 1, 1);
targetView.addTarget('lightMap',			 1, 1);
targetView.addTarget('mirrors',				 1, 1);
