dofile("Scripts//targetview//_targetViewCommon.lua")

targetView.addRow(256)
targetView.addRow(128)

targetView.addTargetCube('EnvCube', 1, 'topSphereAmbient')
targetView.addTargetCube('EnvCube', 1, 'bottomSphereAmbient')
targetView.addCubeHemisphereTop('EnvCube', 1, 0)
targetView.addCubeHemisphereBottom('EnvCube', 1, 0)

targetView.addCubeHemisphereTop('cloudsCube', 2)
targetView.addCubeHemisphereBottom('cloudsCube', 2)
