troops = {
--BOLIVIAN AIR FORCE
	troop('Section Break', _('*BOLIVIAN AIR FORCE*'), 'Bolivian_Air_Force_COA.png'),
	troop('FTA Diablos Negros', _('FTA Diablos Negros'), 'FTA-DN.png'),
	troop('FTA Diablos Rojos', _('FTA Diablos Rojos'), 'FTA-DR.png'),
	troop('GVYCA Interceptors', _('GVYCA Interceptors'), 'GVYCA.png'),
	troop('SNA Gral. Amadeo Saldias Cordero', _('SNA Gral. Amadeo Saldias Cordero'), 'GR_SNA.png'),
	troop('21 Tte. Augusto Escobar Quiroga', _('21 Tte. Augusto Escobar Quiroga'), 'GA_21.png'),
	troop('22 Gral. Alberto Paz Soldan Pol', _('22 Gral. Alberto Paz Soldan Pol'), 'GA_22.png'),
	troop('31 Gral. Jorge Jordan Mercado', _('31 Gral. Jorge Jordan Mercado'), 'GA_31.png'),
	troop('32 Mcal. Bernardino Bilbao Rioja', _('32 Mcal. Bernardino Bilbao Rioja'), 'GA_32.png'),
	troop('33 Cap. Arturo Valle Peralta', _('33 Cap. Arturo Valle Peralta'), 'GA_33.png'),
	troop('34 Tcnl. Rafael Pabon Cuevas', _('34 Tcnl. Rafael Pabon Cuevas'), 'GA_34.png'),
	troop('41 Cap. Arturo Valle Peralta II', _('41 Cap. Arturo Valle Peralta II'), 'GA_41.png'),
	troop('51 Cap. Rafael Estivariz Cardozo', _('51 Cap. Rafael Estivariz Cardozo'), 'GA_51.png'),
	troop('61 Gral. Luis Garcia Pereira', _('61 Gral. Luis Garcia Pereira'), 'GA_61.png'),
	troop('62 Tcnl. Nataniel Verduguez Terceros', _('62 Tcnl. Nataniel Verduguez Terceros'), 'GA_62.png'),
	troop('63 Tcnl. Luis Ernst Rivera', _('63 Tcnl. Luis Ernst Rivera'), 'GA_63.png'),
	troop('64 Gral. Alfredo Santalla Estrella', _('64 Gral. Alfredo Santalla Estrella'), 'GA_64.png'),
	troop('65 Cnl. Amalia Villa de la Tapia', _('65 Cnl. Amalia Villa de la Tapia'), 'GA_65.png'),
	troop('66 Cap. Emilio Beltran Lopez', _('66 Cap. Emilio Beltran Lopez'), 'GA_66.png'),
	troop('67 Gral. Alberto Alarcon Daza', _('67 Gral. Alberto Alarcon Daza'), 'GA_67.png'),
	troop('71 Gral. Walter Arze Rojas', _('71 Gral. Walter Arze Rojas'), 'GA_71.png'),
	troop('72 Cap. Fabian Monasterios Claure', _('72 Cap. Fabian Monasterios Claure'), 'GA_72.png'),
	troop('83 Tcnl. Jose Manuel del Carpio', _('83 Tcnl. Jose Manuel del Carpio'), 'GR_83.png'),
	troop('93 Halcones de la Muerte', _('93 Halcones de la Muerte'), 'ED_93.png'),
	troop('100 Bolivia', _('P1 Bolivia'), 'GP_100.png'),
	troop('GA Mixto', _('GA Mixto'), 'GR_MX.png'),
};
